### PR TITLE
PHPDoc, parameter types, and return types for main classes

### PR DESCRIPTION
**Pull request by thadbryson**
I added the following to:

interface: Respect\Validation\Validatable
classes: 
- Respect\Validation\Validator
- Respect\Validation\Factory

* @PHPDoc for parameters, Exceptions thrown, and return types.
* Parameter type hinting on methods where possible (PHP 7.0).
* Return type hinting on all methods where possible (PHP 7.0). 

I did not type hint the interface because I'd have to type hint all the Rules too. I don't have time for that right now.

### CODE REVIEW

**Comment by nickl-** [comment]
Wow nice work! I didn't even know PHP got type aware lol...

But it's true what you say, we'll have to do all of it and just committing a piece job will only create inconsistencies. Besides @henriquemoody has already been working on a large rewrite at #678 and this would probably fit better pushed against that branch... we'll have to hear what he has to say.

Perhaps you can rally up some support and maybe share this branch with some friends or see if you get some more free time to fill out the rest. It is best to stick to a single goal though, do the type hinting with doc comments and avoiding getting off topic by modifying design patterns. These will just invite more scrutiny, debate and not to forget... testing! Don't let distractions get in the way of your original intentions and lets just get this done. What do you say?

**Comment by thadbryson** [comment]
I'm glad you liked my work. It's nice to be appreciated. I really like the project and want to help. 

I'm fine with merging into whatever branch. Whatever the plan of the project is. 

I think the code should use type hinting wherever possible. It's a feature of PHP 7.0. Really the PHPDoc should be a requirement of the project one way or the other. Use type hinting and PHPDoc or not. 

Although we could have the argument not to use PHPDoc unless necessary. IDEs will pick up the type hinting if it's set which makes PHPDoc unnecessary.

**Comment by henriquemoody** [comment]
Thanks for contributing, @thadbryson! 

I don't think it's worth to update those docblocks once there is this big refactor on #678. 

However, I would really appreciate if you could help me on that PR as well!

🐼

**Comment by thadbryson** [comment]
Thanks. I'll look at that PR.

**Pull request closed without merging**
