### PR TITLE
Add getMessagesIndexedByName() to NestedValidationException

### PR DESCRIPTION
**Pull request by gbhorwood**
for issue 664
https://github.com/Respect/Validation/issues/664

added getMessagesIndexedByName to NestedValidationException with a phpt test.

love your project. use it lots!

### CODE REVIEW

**Comment by henriquemoody** [comment]
Hey, @gbhorwood! Thanks for contributing! 🐼 

I checked your branch but unfortunately this fix doesn't cover nested arrays. Can you change this code to support it?

**Comment by gbhorwood** [comment]
have a deadline crunch for thursday, but will address this right after. thanks for the feedback!

**Comment by henriquemoody** [comment]
Do you have any update on this?

**Comment by rifton007** [comment]
Hi,
I have the version 1.1.15 but I don't have the function getMessagesIndexedByName() in class NestedValidationExceptionn. Why ? Thank you

**Comment by AgustinBrst** [comment]
yess, would love to get this feature! awesome library btw

**Comment by henriquemoody** [comment]
Closed by #957. I've changed how `getMessages()` works. 

Thanks for contributing! 🐼

**Comment by henriquemoody** [comment]
It will be released with the version 2.0. If you want to speed things up, check out #921!

**Pull request closed without merging**
