### PR TITLE
Creates integration tests for Ip rule

### PR DESCRIPTION
**Pull request by batusa**
issue #519

### CODE REVIEW

**Comment by henriquemoody** [comment]
Could you, please, create some tests for `assert()` method with failures?

**Comment by batusa** [comment]
yes sir :+1:  

and one for invalid range (I forgot it) :)

**Comment by batusa** [comment]
@henriquemoody ;)

**Comment by henriquemoody** [comment]
Merged manually by 21c2b4361e8315c5e2802e616c46367060cb6416

Thanks for contributing! :panda_face:

**Pull request closed without merging**
