### PR TITLE
create RuleTestCase

### LINKED ISSUE #492: Create RuleTestCase class in order to make rule tests easier

### PR DESCRIPTION
**Pull request by tonicospinelli**
it is a abstract test class to provide simple way to test rules and
create a mock rule.

fix #492

### CODE REVIEW

**Comment by henriquemoody** [comment]
Can you rebase it to our current master?

You got a broken version of master

**Comment by tonicospinelli** [comment]
@henriquemoody done

**Comment by henriquemoody** [comment]
Merged manually by b4a9253a03af019fe66ed0958c8184c1259af84a and c6638b9ffb04d0645b0fc8785021146a7d7696a0.

This is going to make a lot easier when creating new rules! :smiley: 

Thank you very much for contributing! :panda_face: 

PS.: I'm sorry by my late.

**Comment by tonicospinelli** [comment]
Great!!! Is a pleasure to help!! Go go go 1.0!

**Comment by henriquemoody** [comment]
:dancers:

**Pull request closed without merging**
