### PR TITLE
Add currency code rule.

### LINKED ISSUE #430: Create "CurrencyCode" rule
It must use [ISO 4217](http://en.wikipedia.org/wiki/ISO_4217).

### PR DESCRIPTION
**Pull request by JustinHook**
Closes #430

### CODE REVIEW

**Comment by henriquemoody** [comment]
Merged manually by 4145faab39f7cd76d2f0586c12dba4278ac35fe7

Looks like you just forgot to change the Validator docblock, I have to update the documentation with that step.

Thanks a lot! :panda_face:

**Comment by batusa** [comment]
would you guys consider favor hash lookups over array searches? http://mtdowling.com/blog/2014/03/17/hash-lookups-over-array-search/

**Comment by henriquemoody** [comment]
For an array like this, with 178 items, I'm not sure how much would it make difference, besides I don't see a scenario where validation would be performed for 10000 times, like in the link you sent us, I think this micro-optimization it not worthy to make this code ugly with an associative array which the values will be always the same value.

What you guys think?

**Comment by batusa** [comment]
@henriquemoody I was in doubt about it too. So let's keep it as is.

**Pull request closed without merging**
