### PR TITLE
Improve docs adding namespace import

### PR DESCRIPTION
**Pull request by jomisacu**
Like an example it must be functional. So I've added the import part to be more explicit for newbies.

### CODE REVIEW

**Comment by alganet** [comment]
Hi @jomisacu!

We already have the instructions for namespace import right at the top of the docs:

---

image

---

I believe this introduction should be enough, and save a lot of repetition from the examples. 

Let me know if I'm missing something here! Perhaps there's another reason for adding it and I'm just not getting the idea right.

**Comment by jomisacu** [comment]
> Hi @jomisacu!
> 
> We already have the instructions for namespace import right at the top of the docs:
> 
> image
> 
> I believe this introduction should be enough, and save a lot of repetition from the examples.
> 
> Let me know if I'm missing something here! Perhaps there's another reason for adding it and I'm just not getting the idea right.

Hi @alganet, thanks for the rapid response.

I've noticed the namespace import. Sincerely, I had to check the docs because the example "dosn't work". It isn't a big deal but I think it could be great to have a fully functional example for the reasons below:

- v is not a real element on the respect/validation context, using it as static class lead to confusion
- Newbies can start using the library just following the examples due them are functional

Again, it isn't a big deal, feel free to close this PR I'll be happy to contribute in other way. However I think it could be worthy.

Thanks!

**Comment by henriquemoody** [comment]
It can indeed be a bit of an issue to have those examples that don't work. However, I think that adding those `use` to every docblock is not ideal ether.

You gave me an idea, though, @jomisacu! What if we ship this peace of code with the library?

```php
if (!class_exists('v') ) {
    class_alias(Respect\Validation\Validator::class, 'v');
}
```

With this, we'll always have `v` as an alias to the original class, it will make using the library much simpler.

Any thoughts?

**Comment by henriquemoody** [comment]
Hi @jomisacu!

I appreciate you taking the time to make those changes, but I would like to keep the documentation a bit simpler. Besides, at this point there would be too many files for you to change.

Regardless, thank you very much for contributing this made me think about how to have better documentation and for that I'm grateful already! 🐼

**Comment by jomisacu** [comment]
Hi @henriquemoody!

Thanks for your time.

**Pull request closed without merging**
