### PR TITLE
Make Roman rule internally use Regex rule

### PR DESCRIPTION
**Pull request by l-x**
Just for consistency... :smile:

### CODE REVIEW

**Comment by henriquemoody** [comment]
Since you're doing that, can you extend Regex rule instead? (like [Yes](https://github.com/Respect/Validation/blob/master/library/Rules/Yes.php#L13) rule)

**Comment by l-x** [comment]
I considered doing so. IMO the Roman Rule is not a special Regexp Rule, it just utilizes the Regexp Rule. Solving this by inheritance would break the OOP design principles.

**Comment by henriquemoody** [comment]
The `Regex` rule has no specific method signature, only the same of `AbstractRule`; and a public variable `$regex` which, if needed, can be used (and useful) on `Roman` context as well, think about it:

```php
function validateAndExplain(Regex $regex, $input)
{
    if (!$regex->validate($input)) {
        echo $input.' is not valid for REGEXP '.$regex->regex.PHP_EOL;
    }
}

validateAndExplain($regex, $input);
validateAndExplain($roman, $input);
validateAndExplain($yes, $input);
validateAndExplain($not, $input);
```

I know, _Roman is not Regex_, but I think better we do this than create a hard coded instance of `Regex` inside `Roman::validate()` which would break OOD principles too and, IMHO, worse them use inheritance in this case.

Unfortunately we also have other design problems and we have plans to use a different design (but keeping the fluent API) in the first major release.

**Comment by l-x** [comment]
Ok, I've updated the PR.

**Comment by henriquemoody** [comment]
Thank for contributing! :smile:

**Pull request merged**
