### PR TITLE
Test against PHP 7.2

### PR DESCRIPTION
**Pull request by carusogabriel**
With the release of [`PHP 7.2`](http://php.net/archive/2017.php#id2017-11-30-1), would be interesting to test it.

### CODE REVIEW

**Comment by henriquemoody** [comment]
In that case you also need to upgrade PHPUnit to version 5

**Comment by carusogabriel** [comment]
I’ll add support to it in another PR 👨🏻‍💻

**Comment by carusogabriel** [comment]
Actually, as we already test PHP 7.2 on master, should we do it to 1.1?

**Comment by henriquemoody** [comment]
That would be good, but we need to upgrade PHPUnit fist since PHPUnit 4 fails on PHP 7.2.

**Comment by carusogabriel** [comment]
Upgrade or add support? As PHPUnit 5 requires PHP 5.6 :sweat_smile:

**Comment by henriquemoody** [comment]
I'm sorry that I didn't reply, sometimes I get lost with the GitHub notifications. 

I don't think we should add support to a new version of PHPUnit in version that was already released. `master` has support for PHP 7.2, though, tests are running fine. :)

**Pull request closed without merging**
