### PR TITLE
Making real tests for `Exists` and integration tests added

### PR DESCRIPTION
**Pull request by KennedyTedesco**
This is just a proposal because it's not so bad the test with a real file. Or this approach is somehow problematic?

### CODE REVIEW

**Comment by henriquemoody** [comment]
I'm not sure about what is the benefits of this change. I would rather use [vfsStream](http://vfs.bovigo.org/) like we do on [SizeTest](https://github.com/Respect/Validation/blob/master/tests/unit/Rules/SizeTest.php#L102-L111) for that.

**Comment by KennedyTedesco** [comment]
Yeah, that's fair enough. If you want to I can send a new one PR using vfsStream. Or we just maintain the current implementation.

**Comment by henriquemoody** [comment]
If you don't mind, just send thought this pull request

**Comment by KennedyTedesco** [comment]
Now i'm happy with this. :) If there is anything more that I have to do, please let me know.

**Comment by henriquemoody** [comment]
Merged manually by 7d8b18bacae9967912e4acf0fdc3e88be13cf56a

Thanks for contributing! :panda_face:

**Comment by KennedyTedesco** [comment]
:beers:

**Pull request closed without merging**
