### PR TITLE
Make inputs optional

### LINKED ISSUE #235: Different results for validate(), assert() and check()
Am I doing something wrong? 
Why assert and check don't throw exception?
```php
use Respect\Validation\Validator as v;

$array = array('foo' => '');
var_dump(v::key('foo', v::positive())->validate($array)); // false
var_dump(v::key('foo', v::positive())->assert($array)); // true
var_dump(v::key('foo', v::positive())->check($array)); // true
```

### PR DESCRIPTION
**Pull request by henriquemoody**
Fix #235

### CODE REVIEW

**Comment by henriquemoody** [comment]
Hey @Respect/troubleshooters, I'm really considering doing that for 1.0.

It's the only BC break I would consider for the first major version (1.0). I really need your attention here.

**Comment by augustohp** [comment]
It is a pretty big BC break is it not? I'd rather have current API as is.

**Comment by henriquemoody** [comment]
Yes it is, in the other hand that's how the library should work...

**Comment by augustohp** [comment]
This defeats the purpose of keeping a compatible API doesn't it?




Although I am not against the idea, I am inclined to believe it defeats the purpose of keeping an old compatible API.

**Comment by henriquemoody** [comment]
I don't see like that.

It's really a huge BC break, but this PR keeps the same _Concrete API_ we already (discussed in #354), but it changes the way to create rules indeed.

**Comment by henriquemoody** [comment]
Since there was no agreement on that, I closed this pull request.

Any way, I'm not sure how we can proceed with the 1.0 version. I'm not really comfortable to release it as is specially because of the _optional input_ problem.

This pull request was only a alternative to the problem, but it's a very poor solution. Perhaps we should remove the _optional input_ and just create the `optional()` rule to handle this situation, I don't know...

What I do know is that we have to release 1.0 on Oct 24 and there is a lot to talk about it until them and that also we have 2.0 to release but we don't even finished the discussions about the new Concrete API and I don't wanna make the decisions by myself, it's not how I wanna do that.

**Pull request closed without merging**
