### PR TITLE
Update AgeException.php

### PR DESCRIPTION
**Pull request by AchrafSoltani**
Although the rule age doesn't seem to be used or parsed correctly by the factory

### CODE REVIEW

**Comment by henriquemoody** [comment]
Can you elaborate?

**Comment by AchrafSoltani** [comment]
when calling v::age(), nothing seems to happen and it says that it's not a valid rule ... travis tests seems to confirm what I say

**Comment by henriquemoody** [comment]
Actually Travis says you changed the exception message:

```text
1) Respect\Validation\Rules\AgeTest::testShouldThrowsExceptionWhenMinimumAgeFails
Failed asserting that exception message '"today" must be greater than 18 years' contains '"today" must be lower than 18 years ago'.

2) Respect\Validation\Rules\AgeTest::testShouldThrowsExceptionWhenMaximunAgeFails
Failed asserting that exception message '"51 years ago" must be lower than 50 years' contains '"51 years ago" must be greater than 50 years ago'.

3) Respect\Validation\Rules\AgeTest::testShouldThrowsExceptionWhenMinimunAndMaximunAgeFails
Failed asserting that exception message '"today" must be between 18 and 50 years' contains '"today" must be between 18 and 50 years ago'.
```

Also, things like `v::age(18)->validate('18 years ago')` are working.
You must consider that `age()` is still in our master branch, which are not released since version 0.8. Age rule will be release in 0.9 version.

What version are you using?

**Comment by AchrafSoltani** [comment]
"respect/validation": "0.8.*"

I'm using phpstorm and it's able to give me insights about a given class, both phpstorm and the webserver reported that the age rule doesn't exist.

I guess you explained all, I was checking the source code of the master branch while using the 8.* for dev

**Comment by henriquemoody** [comment]
I will close this pull request since we already solved your problem.

**Pull request closed without merging**
