### PR TITLE
Issue #855 - Support Twitch Video URL

### PR DESCRIPTION
**Pull request by sprak3000**
* Adds a `twitch:video` and `twitch:clip` URL patterns to the `VideoUrl` rule. Videos are created by the Twitch channel owner. Clips are created by people watching a channel. Kept them separate for ease of regexp creation and because they are different types of content on the Twitch platform.
* Updated unit tests to include the new URL patterns.
* Updated documentation to include the new URL patterns.

### CODE REVIEW

**Comment by henriquemoody** [comment]
Thanks for contributing, @sprak3000. 

Would it be better to only have `twitch`, with the regex `@^https?://((www|clips)\.)?twitch\.tv/(videos/[0-9]+|[a-zA-Z0-9]+)$@i`?

**Comment by sprak3000** [comment]
@henriquemoody 

I considered that. Videos and clips are two different "things" in Twitch, but I'm not sure if the distinction would matter that much. The regex would have to be adjusted slightly though. The `clips` URL is only valid for the non-numeric URL portion. Wouldn't be too difficult to sort out.

**Comment by henriquemoody** [comment]
Wouldn't that REGEX I wrote satisfy these conditions?

**Comment by sprak3000** [comment]
@henriquemoody 

I've updated the PR to just have a `twitch` video URL service instead of the two separate.

**Comment by batusa** [comment]
@sprak3000 I've gathered your changes in this Pull Request https://github.com/Respect/Validation/pull/1154

Thanks a lot for contributing! 🐼

**Pull request closed without merging**
