### PR TITLE
Implemented an XOR group check as onlyOneOf

### LINKED ISSUE #765: Support for XOR or rules
You are currently able to check for `AllOf` (logical AND), `NoneOf` (negative logical AND) and `OneOf` (logical OR), but you are not able to do `OnlyOneOf` (logical XOR).

Here is a simple expected result case:

```php
$set = [
    v::key('one'),
    v::key('two')
];

v::allOf(...$set)->validate(['one' => 'yes', 'two' => 'no']); // true
v::allOf(...$set)->validate(['one' => 'yes']); // false

v::noneOf(...$set)->validate(['one' => 'yes', 'two' => 'no']); // false
v::noneOf(...$set)->validate(['one' => 'yes']); // false

v::oneOf(...$set)->validate(['one' => 'yes', 'two' => 'no']); // true
v::oneOf(...$set)->validate(['one' => 'yes']); // true

v::onlyOneOf(...$set)->validate(['one' => 'yes', 'two' => 'no']); // false
v::onlyOneOf(...$set)->validate(['one' => 'yes']); // true
```

### PR DESCRIPTION
**Pull request by bradynpoulsen**
Closes #765

### CODE REVIEW

**Comment by henriquemoody** [comment]
Thanks for contributing! I'm waiting for #678 to be completed.

Also, I feel like `oneOf` is actually `someOf`, and the one that you send would be `oneOf`. I need to sleep on it...

**Comment by bradynpoulsen** [comment]
@henriquemoody Will `someOf` have a constraint to fulfill the plural number of "some", like the minimum that must pass for it to be accepted? (ie, `someOf(2, $rule1, $rule2, $rule3, $rule4)`). If not, I would recommend considering `anyOf` since only one needs to validate

**Comment by henriquemoody** [comment]
Hey @bradynpoulsen, can you take a look on #787?

**Comment by henriquemoody** [comment]
It was merged by #787 with some changes.

Thanks for contributing! 🐼

**Pull request closed without merging**
