### PR TITLE
Add method Identical To Validator.php

### PR DESCRIPTION
**Pull request by mprince**
I am not sure if this was missing while working in this https://github.com/Respect/Validation/pull/442 or was it left out on purpose.

### CODE REVIEW

**Comment by mprince** [comment]
@henriquemoody could you please take a look. Thanks.

**Comment by batusa** [comment]
it's really missing...

he'll merge it asap. thanks! :)

**Comment by henriquemoody** [comment]
I'm sorry by my late. It was merged manually by 6597aa51149aff674faa9db1729c0c70392aa296.

Thanks for contributing! 🐼

**Comment by henriquemoody** [comment]
The documentation is already available on [our documentation](respect.github.io/Validation/docs/validators.html) and on versions 1.0.7 and 1.1.2.

**Pull request closed without merging**
