### PR TITLE
Add base64 rule

### PR DESCRIPTION
**Pull request by jenssegers**
This PR adds a base64 rule to check if a value is base64 encoded.

### CODE REVIEW

**Comment by Singwai** [comment]
https://en.wikipedia.org/wiki/Base64

**Comment by jenssegers** [comment]
Any updates?

**Comment by Singwai** [comment]
I think there are a few improvements can be done in the regex. I will work on it this weekend.

**Comment by henriquemoody** [comment]
Merged by #865

Thanks for contributing! 🐼

**Pull request closed without merging**
