### PR TITLE
Removed Key Prefix

### PR DESCRIPTION
**Pull request by noobshow**
Most Validation errors are sent to Users/Visitors or Clients and as such, they might not need to know it was a Key their inputs are being validated upon.

The PR can be rejected if it seems not a valid point or there's a way to change Rules\Key() errors.

Thanks

### CODE REVIEW

**Comment by CameronHall** [comment]
@noobshow you'll need to update the tests as well :)

**Comment by noobshow** [comment]
> @noobshow you'll need to update the tests as well :)

Will do that now...

**Comment by noobshow** [comment]
> @noobshow you'll need to update the tests as well :)

Updated the tests and seems valid, but some composer requirements couldn't pass for HP 8.0.0

**Comment by henriquemoody** [comment]
Merged by 029fa7fe73521b2485076bcfaae4c4e9e859b1fa

Thanks for contributing! 🐼

**Pull request closed without merging**
