### PR TITLE
Add NotEmoji Rule

### PR DESCRIPTION
**Pull request by mazentouati**
Hey there,
This pull request bring a new validator as mentioned in this issue #1173 .

Checking the emoji is very tricky as their Unicode ranges are spread, so I used the official reference for the Unicode v11 to gather the emoji data. I created a script to scrap, organize and handle these information to generate an optimized Regex pattern that's able to catch the emoji.

### CODE REVIEW

**Comment by mazentouati** [comment]
Any thoughts why the style fixing command cause Travis to fail when building for PHP7.2 ?. Thought, it works locally with PHP7.2.2.
```
vendor/bin/php-cs-fixer --diff --dry-run --verbose fix
```

It throws the following error on travis
```
PHP Fatal error:  Class 'null' not found in /home/travis/build/Respect/Validation/vendor/symfony/options-resolver/OptionsResolver.php on line 1004
```

**Comment by mazentouati** [comment]
I found the issue source : it's this line in Travis Config : 
` - pecl install uopz || echo "Cound not install uopz" 1>&2`
because the extension `uopz` will cause `symfony/options-resolver` that's used by PHP-cs-fixer to fail. Though when ignoring the extension it will cause the integration test for the Upload.phpt to fail. I don't know what you like to do either drop the use of the extension and the Upload test or ignore the build fail.

**Comment by henriquemoody** [comment]
Hey, @mazentouati! 

You did some amazing work in this PR! 🎉 

I'm sorry by my delay, I switched jobs recently and things are still a bit busy, but I should get back now!

I sent #1182 with a few changes to your code, but nothing compared to the work you've done!

Thank you very much for contributing! 🐼

**Comment by mazentouati** [comment]
Oh Great Thanks ^^, thought I'll PR a more accurate ranges later on this night. I'll provide more details...

**Pull request closed without merging**
