### PR TITLE
Validate the age to be always be an integer

### LINKED ISSUE #593: MinimunAge rule should not check if age is an integer type
On [MinimumAge](https://github.com/Respect/Validation/blob/master/library/Rules/MinimumAge.php#L29-L31) rule, it checks if the input is an integer, but instead is must use `filter_var()` with `FILTER_VALIDATE_INT` to also accept also integer numbers as string types.

### PR DESCRIPTION
**Pull request by diegoholiveira**
Closes #593

### CODE REVIEW

**Comment by henriquemoody** [comment]
It's fixed already by b98595a5c093bfebd8686646fffb6b441fce6a08

However, thanks for contributing, @diegoholiveira, it's a pleasure to see you around! :panda_face:

**Comment by diegoholiveira** [comment]
@henriquemoody: it would be nice to find a way to avoid two people working on the same issue.

**Comment by henriquemoody** [comment]
That's true, unfortunately GitHub doesn't provide a smart way to do this. I'm going to write a process and put it on CONTRIBUTING.md file.

I'm sorry about the inconvenient. :confused:

**Comment by diegoholiveira** [comment]
There is no problem about this. It's more important to have this issue solved, no matter who did it.

But this can happen again. And with something bigger than just a few lines... and this really concerns me.

**Comment by henriquemoody** [comment]
Do you have any suggestions?

**Comment by KennedyTedesco** [comment]
I guess this is something that we have to look before send a PR. Right? Mostly because doesn't exist a way to avoid this by using a tool, for example.

**Comment by batusa** [comment]
let's take this issue to an issue :stuck_out_tongue: https://github.com/Respect/Validation/issues/605

**Pull request closed without merging**
